---
title: "Statistics"
author: "Sumon Barua"
output:
  html_document:
    keep_md: true
    fig_width: 4
    fig_height: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
```
####Normal Density

```{r}
x.values <- seq(40, 160, 1)
x.sd.values <- seq(40, 160, 15)
x.zeros.values <- rep(0, 9)

ggplot(data = NULL, aes(x = x.values, y = dnorm(x.values, 100, 15))) +
  geom_line() +
  labs(x = "x", y = "f(x)") + 
  scale_x_continuous(breaks = x.sd.values, labels = x.sd.values) +
  geom_segment((
      aes( x = x.sd.values, y = x.zeros.values, xend = x.sd.values, yend = dnorm(x.sd.values, m = 100, s = 15))
              ), linetype = "dashed") +
  scale_y_continuous( expand = c( 0,0))
```


####Sampling Distribution

```{r}
library(ggplot2)

#population
values <- c( 10,20,30,40)
#probabilities
probabilities <- c( 1/4, 1/4, 1/4, 1/4)
#store sample means
smpl.means <- NULL

set.seed( 123)

for( i in 1: 1000)
{ 
  #generate sample
  smpl <- sample( x = values, prob = probabilities, size = 4, replace = TRUE) 
  #append to vector - mean of the above sample
  smpl.means <- append( smpl.means, mean( smpl)) 
}

#Histogram - Normal distribution
ggplot( NULL, aes( x = smpl.means)) + 
  geom_histogram()

#unique values - for x-axis labeling
m.values <-round( unique( smpl.means), 2)


ggplot( NULL, aes( x = smpl.means)) + 
  geom_histogram() + 
  scale_x_continuous( breaks = m.values, label = m.values) + 
  scale_y_continuous( expand = c( 0,0)) + 
  labs( x = expression( bar( X)), y = expression (frequency( bar( X))))


```
